## Numpy Basics To Advance

In [3]:
import numpy as np

Create a 1D NumPy array containing the integers from 0 to 9.

In [4]:
 array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [5]:
array_2d = np.random.randint(1, 21, (3, 3))
print("2D Array:", array_2d)

2D Array: [[13 18 10]
 [12 13  2]
 [13  6 12]]


Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [6]:
array_3d = np.ones((2, 3, 4))
print("3D Array:", array_3d)

3D Array: [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Add two 1D arrays element-wise.

In [7]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([10, 20, 30, 40, 50])
sum_arrays = array_a + array_b
print("Sum of Arrays:", sum_arrays)

Sum of Arrays: [11 22 33 44 55]


Multiply two 2D arrays element-wise.

In [8]:
array_x = np.random.randint(1, 10, (3, 3))
array_y = np.random.randint(1, 10, (3, 3))
product_arrays = array_x * array_y
print("Product of 2D Arrays:", product_arrays)

Product of 2D Arrays: [[25 20 24]
 [36  8 56]
 [49 72 25]]


Calculate the dot product of two matrices.

In [9]:
dot_product = np.dot(array_x, array_y)
print("Dot Product:", dot_product)

Dot Product: [[117  93  83]
 [148  92 108]
 [151  84 109]]


Calculate the mean, median, and standard deviation of a 1D array.

In [10]:
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_dev_value = np.std(array_1d)
print("Mean:", mean_value, "Median:", median_value, "Std Dev:", std_dev_value)

Mean: 4.5 Median: 4.5 Std Dev: 2.8722813232690143


Generate an array of 1000 random numbers from a normal distribution with a mean of 0
and a standard deviation of 1.

In [12]:
normal_distribution = np.random.normal(0, 1, 1000)
print("First 10 Normal Dist Values:", normal_distribution[:10])

First 10 Normal Dist Values: [-1.35109774  0.03704368  1.61895024 -1.43191227 -0.1592665   0.85914358
 -1.06888406  1.84620172 -2.1429315  -0.38451585]


 Find the maximum and minimum values in a 2D array.

In [11]:
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("Max:", max_value, "Min:", min_value)

Max: 18 Min: 2


Create a 2D array of shapes (5, 5) with random integers from a uniform distribution
between 10 and 50.

In [13]:
uniform_array = np.random.randint(10, 51, (5, 5))
print("Uniform Array:", uniform_array)

Uniform Array: [[16 29 47 40 50]
 [14 27 23 14 25]
 [31 40 26 43 45]
 [40 46 30 47 48]
 [33 24 39 24 17]]


Calculate the cumulative sum of a 1D array.

In [14]:
cumulative_sum = np.cumsum(array_1d)
print("Cumulative Sum:", cumulative_sum)

Cumulative Sum: [ 0  1  3  6 10 15 21 28 36 45]


 Compute the correlation coefficient matrix of a 2D array.

In [15]:
correlation_matrix = np.corrcoef(array_2d)
print("Correlation Matrix:\n", correlation_matrix)

Correlation Matrix:
 [[ 1.         0.8339031 -0.8714204]
 [ 0.8339031  1.        -0.4559475]
 [-0.8714204 -0.4559475  1.       ]]


 Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [16]:
die_rolls = np.random.randint(1, 7, 1000)
unique, counts = np.unique(die_rolls, return_counts=True)
die_frequencies = dict(zip(unique, counts))
print("Die Roll Frequencies:", die_frequencies)

Die Roll Frequencies: {np.int32(1): np.int64(158), np.int32(2): np.int64(157), np.int32(3): np.int64(175), np.int32(4): np.int64(160), np.int32(5): np.int64(172), np.int32(6): np.int64(178)}


Extract a 3x3 sub-array starting from position (1,1) in a (5,5) array

In [21]:
array_5x5 = np.random.randint(1, 21, (5, 5))
sub_array_3x3 = array_5x5[1:4, 1:4]
print(array_5x5)
print("\n\n",sub_array_3x3)

[[ 1 17  6 20 20]
 [ 3  3  3 14 15]
 [ 6 18  2  5  4]
 [19 18  5  3  3]
 [ 2 16 12 13 16]]


 [[ 3  3 14]
 [18  2  5]
 [18  5  3]]


Extract first two rows and all columns of the second slice along axis 2 in a (4,3,2) array

In [26]:
array_4x3x2 = np.random.randint(1, 21, (4, 3, 2))
sub_array_2x3 = array_4x3x2[:2, :, 1]
print("Extracted sub-array:", sub_array_2x3)

Extracted sub-array: [[18 20 15]
 [ 7  8 14]]


 Fancy indexing to extract elements at positions [1, 3, 4, 7]

In [27]:
array_1d = np.arange(10)
fancy_extracted = array_1d[[1, 3, 4, 7]]
print("Fancy indexed elements:", fancy_extracted)

Fancy indexed elements: [1 3 4 7]


Fancy indexing to select rows [0, 2, 3] and columns [1, 3]

In [28]:
array_2d = np.random.randint(1, 21, (5, 5))
fancy_rows_cols = array_2d[[0, 2, 3], :][:, [1, 3]]
print("Selected rows and columns:", fancy_rows_cols)

Selected rows and columns: [[18 10]
 [18 16]
 [12 12]]


 Extract all elements greater than 10 from a 1D array

In [32]:
filtered_array = array_1d[array_1d > 10]
print("Elements > 10:", filtered_array)


Elements > 10: []


 Replace all elements greater than 15 with 0 in a (5,5) array

In [30]:
array_5x5[array_5x5 > 15] = 0
print("Modified array:", array_5x5)

Modified array: [[ 1  0  6  0  0]
 [ 3  3  3 14  6]
 [ 6  0  2  5  0]
 [ 0  0  5  3  0]
 [ 2  0 12 13  0]]


Add a (3,) array to each row of a (4,3) array

In [33]:
array_4x3 = np.random.randint(1, 10, (4, 3))
array_1d_3 = np.array([1, 2, 3])
broadcast_sum = array_4x3 + array_1d_3
print("Broadcast sum:", broadcast_sum)

Broadcast sum: [[10  6 11]
 [10 10  4]
 [ 4  7 11]
 [ 4  4 12]]


 Multiply a (3,3) array by a (3,) array

In [34]:
array_3x3 = np.random.randint(1, 10, (3, 3))
broadcast_product = array_3x3 * array_1d_3
print("Broadcast product:", broadcast_product)

Broadcast product: [[ 2 12  3]
 [ 1  6 15]
 [ 9 10  3]]


Perform element-wise addition of (3,1) and (1,4) arrays

In [35]:
array_3x1 = np.random.randint(1, 10, (3, 1))
array_1x4 = np.random.randint(1, 10, (1, 4))
broadcast_addition = array_3x1 + array_1x4
print("Broadcast addition:", broadcast_addition)

Broadcast addition: [[ 9 11 10  8]
 [ 8 10  9  7]
 [11 13 12 10]]


Add a (3,4) array to each 2D slice along the first axis of a (2,3,4) array

In [36]:
array_2x3x4 = np.random.randint(1, 10, (2, 3, 4))
array_3x4 = np.random.randint(1, 10, (3, 4))
broadcast_3D_addition = array_2x3x4 + array_3x4
print("Broadcast 3D addition:", broadcast_3D_addition)

Broadcast 3D addition: [[[17  4 13 18]
  [ 9  9  7  8]
  [11  9 12  6]]

 [[17  4  9 16]
  [ 7 17  9  9]
  [10  7 16 11]]]


 Extract every second row and column, then add a 1D array to each row

In [37]:
sliced_2d = array_2d[::2, ::2]
sliced_2d_broadcast = sliced_2d + array_1d_3[:sliced_2d.shape[1]]
print("Sliced and broadcasted array:", sliced_2d_broadcast)


Sliced and broadcasted array: [[ 4 21 18]
 [ 2  7 14]
 [17  8  6]]


Extract sub-array from (4,3,2) and subtract a (3,2) array using broadcasting

In [38]:
sub_3D = array_4x3x2[:2, :, :]
array_3x2 = np.random.randint(1, 10, (3, 2))
broadcast_subtraction = sub_3D - array_3x2
print("Broadcast subtraction:", broadcast_subtraction)

Broadcast subtraction: [[[ 7 10]
  [13 19]
  [ 8  7]]

 [[ 3 -1]
  [-4  7]
  [ 1  6]]]


Extract diagonal elements of a 2D array

In [39]:
array_diag = np.diag(array_2d)
print("Diagonal elements:", array_diag)


Diagonal elements: [ 3 14  5 12  3]


 Reverse order of elements in each row of a 2D array

In [40]:
reversed_rows = array_2d[:, ::-1]
print("Reversed rows:", reversed_rows)

Reversed rows: [[15 10 19 18  3]
 [15 18 20 14 10]
 [11 16  5 18  1]
 [19 12  9 12  2]
 [ 3 20  6  8 16]]


Extract (2,3,4) sub-array from (4,5,6) and add (4,) array to each row along axis 2

In [41]:
array_4x5x6 = np.random.randint(1, 10, (4, 5, 6))
sub_2x3x4 = array_4x5x6[:2, :3, :4]
array_4 = np.random.randint(1, 10, (4,))
broadcast_3D_addition_2 = sub_2x3x4 + array_4[np.newaxis, np.newaxis, :]
print("Broadcast 3D addition 2:", broadcast_3D_addition_2)

Broadcast 3D addition 2: [[[ 4 16  9 16]
  [10 13  6 13]
  [ 4 10 11 11]]

 [[ 5 15 11 10]
  [ 7  9 12 16]
  [ 9 11  6 15]]]


Set last column of a (5,5) array to sum of first two columns

In [42]:
array_5x5[:, -1] = array_5x5[:, 0] + array_5x5[:, 1]
print("Updated array with column sum:", array_5x5)

Updated array with column sum: [[ 1  0  6  0  1]
 [ 3  3  3 14  6]
 [ 6  0  2  5  6]
 [ 0  0  5  3  0]
 [ 2  0 12 13  2]]
